apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-function-deploy
  labels:
    application: scmcontacts
    service: searchfunc
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      application: scmcontacts
      service: searchfunc
  template:
    metadata:
      labels:
        application: scmcontacts
        service: searchfunc
    spec:
      automountServiceAccountToken: false
      containers:
        - name: application
          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '500m'
          image: <ACR_NAME>.azurecr.io/adc-search-func:2.0
          env:
            - name: WEBSITE_SITE_NAME
              value: func-search-indexer
            - name: AzureWebJobsDashboard
              valueFrom:
                secretKeyRef:
                  name: scmsecrets
                  key: FUNCTIONSCONNECTIONSTRING
            - name: AzureWebJobsStorage
              valueFrom:
                secretKeyRef:
                  name: scmsecrets
                  key: FUNCTIONSCONNECTIONSTRING
            - name: ServiceBusConnectionString
              valueFrom:
                secretKeyRef:
                  name: scmsecrets
                  key: CONTACTSLISTENCONNSTR
            - name: FUNCTIONS_WORKER_RUNTIME
              value: dotnet
            - name: FUNCTIONS_EXTENSION_VERSION
              value: '~3'
            - name: ContactIndexerOptions__IndexName
              value: scmcontacts
            - name: ContactIndexerOptions__ServiceName
              valueFrom:
                secretKeyRef:
                  name: scmsecrets
                  key: SEARCHNAME
            - name: ContactIndexerOptions__AdminApiKey
              valueFrom:
                secretKeyRef:
                  name: scmsecrets
                  key: SEARCHPRIMARYKEY
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: scmsecrets
                  key: APPINSIGHTSKEY
          imagePullPolicy: IfNotPresent
