pr: none
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - day7/apps/dotnetcore/Scm.Resources/Adc.Scm.Resources.ImageResizer/*
      - day7/apps/dotnetcore/manifests/scmresourcesfunc/*
      - day7/apps/pipelines/cd-scm-resources-func.yaml

variables:
  configuration: release
  azureSubscription: AzureDeveloperCollege
  containerRegistry: ADC-ContainerRegistry

stages:
  - stage: Build
    displayName: Build

    jobs:
      - template: jobs/build-scm-resources-func.yaml
        parameters:
          configuration: $(configuration)
          buildNumber: $(Build.BuildNumber)
          containerRegistryServiceConnection: $(containerRegistry)

  - stage: Development
    displayName: Development
    dependsOn: Build

    jobs:
      - template: jobs/deploy-scm-resources-func.yaml
        parameters:
          name: Deploy Scm Resources Indexer Function
          keyVaultVariableGroupName: Day7-KeyVault-Dev
          buildNumber: $(Build.BuildNumber)
          environmentName: ADC-DAY7-SCM-DEV
          azureSubscription: $(azureSubscription)
          containerRegistry: $(containerRegistry)
          clusterNamespace: contactsapp
