apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: mysqldb
        image: day6demo.azurecr.io/mysql:v1 # update the image name
        ports:
        - containerPort: 3306
          name: mysqldb
        env:
        - name: MYSQL_DATABASE
          value: "project"
        - name: MYSQL_USER
          value: "projectmaster"
        - name: MYSQL_PASSWORD
          value: "master1234"
        - name: MYSQL_ROOT_PASSWORD
          value: "master1234"
---
apiVersion: v1
kind: Service
metadata: 
  name: mysqldb
spec:
  ports:
  - port: 3306
  selector:
    app: mysqldb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: phpapp
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: phpapp
        image: day6demo.azurecr.io/php:v1 # update the image name
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: DB_SERVER
          value: "mysqldb"
        - name: DB_USERNAME
          value: "projectmaster"
        - name: DB_PASS
          value: "master1234"
        - name: DB_NAME
          value: "project"
---
apiVersion: v1
kind: Service
metadata:
  name: phpapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: phpapp