name: day2-scm-cleanup

on:
  workflow_dispatch:

jobs:
  destroy:
    if: github.repository == 'azuredevcollege/trainingdays'
    runs-on: ubuntu-latest
    env:
      RG_DEV: rg-scm-devday2
      RG_TEST: rg-scm-testday2

    steps:
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Destroy resource groups
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            az group delete -n ${{ env.RG_DEV }} -y
            az group delete -n ${{ env.RG_TEST }} -y
